# tenants/migrations/0001_initial.py
# Generated by Django 4.2 on YYYY-MM-DD HH:MM

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantConfig',
            fields=[
                ('tenant_id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_name', models.CharField(max_length=100, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('schema_name', models.CharField(max_length=63, unique=True)),
            ],
            options={
                'db_table': 'public.tenant_config',
            },
        ),
        migrations.CreateModel(
            name='TenantDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('domain', models.CharField(db_index=True,
                                            max_length=253,
                                            unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='domains',
                                             to='tenants.tenantconfig')),
            ],
            options={
                'db_table': 'tenant_domain',
            },
        ),
    ]