# Generated by Django 4.2 on 2025-02-25 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the assessment", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional description"),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "assessment",
            },
        ),
        migrations.CreateModel(
            name="IRO",
            fields=[
                ("iro_id", models.AutoField(primary_key=True, serialize=False)),
                ("current_version_id", models.IntegerField(blank=True, null=True)),
                ("current_stage", models.CharField(default="Draft", max_length=50)),
                ("type", models.CharField(max_length=20)),
                (
                    "source_of_iro",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "esrs_standard",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_assessment_date", models.DateTimeField(blank=True, null=True)),
                ("assessment_count", models.IntegerField(default=0)),
                (
                    "last_assessment_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenantconfig",
                    ),
                ),
            ],
            options={
                "db_table": "iro",
            },
        ),
        migrations.CreateModel(
            name="IROVersion",
            fields=[
                ("version_id", models.AutoField(primary_key=True, serialize=False)),
                ("version_number", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "sust_topic_level1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "sust_topic_level2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "sust_topic_level3",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("value_chain_lv1", models.JSONField(default=list)),
                ("value_chain_lv2", models.JSONField(default=list)),
                ("economic_activity", models.JSONField(default=list)),
                ("status", models.CharField(default="Draft", max_length=50)),
                ("created_by", models.IntegerField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("parent_version_id", models.IntegerField(blank=True, null=True)),
                ("split_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "iro",
                    models.ForeignKey(
                        db_column="iro_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessments.iro",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenantconfig",
                    ),
                ),
            ],
            options={
                "db_table": "iro_version",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("review_id", models.AutoField(primary_key=True, serialize=False)),
                ("reviewer_id", models.IntegerField()),
                ("status", models.CharField(default="Draft", max_length=50)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "iro",
                    models.ForeignKey(
                        db_column="iro_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessments.iro",
                    ),
                ),
                (
                    "iro_version",
                    models.ForeignKey(
                        blank=True,
                        db_column="iro_version_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="assessments.iroversion",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenantconfig",
                    ),
                ),
            ],
            options={
                "db_table": "review",
            },
        ),
        migrations.CreateModel(
            name="Signoff",
            fields=[
                ("signoff_id", models.AutoField(primary_key=True, serialize=False)),
                ("signed_by", models.IntegerField()),
                ("signed_on", models.DateTimeField(auto_now_add=True)),
                (
                    "signature_ref",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("comments", models.TextField(blank=True, default="")),
                (
                    "iro_version",
                    models.ForeignKey(
                        blank=True,
                        db_column="iro_version_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="assessments.iroversion",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        db_column="review_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessments.review",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenantconfig",
                    ),
                ),
            ],
            options={
                "db_table": "signoff",
            },
        ),
        migrations.CreateModel(
            name="RiskOppAssessment",
            fields=[
                (
                    "risk_opp_assessment_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "fin_materiality_def_version_id",
                    models.IntegerField(blank=True, null=True),
                ),
                ("time_horizon", models.CharField(max_length=20)),
                ("workforce_risk", models.IntegerField(blank=True, null=True)),
                ("workforce_risk_rationale", models.TextField(blank=True, null=True)),
                ("operational_risk", models.IntegerField(blank=True, null=True)),
                ("operational_risk_rationale", models.TextField(blank=True, null=True)),
                ("cost_of_capital_risk", models.IntegerField(blank=True, null=True)),
                (
                    "cost_of_capital_risk_rationale",
                    models.TextField(blank=True, null=True),
                ),
                ("reputational_risk", models.IntegerField(blank=True, null=True)),
                (
                    "reputational_risk_rationale",
                    models.TextField(blank=True, null=True),
                ),
                ("legal_compliance_risk", models.IntegerField(blank=True, null=True)),
                (
                    "legal_compliance_risk_rationale",
                    models.TextField(blank=True, null=True),
                ),
                ("likelihood_score", models.IntegerField(blank=True, null=True)),
                ("likelihood_rationale", models.TextField(blank=True, null=True)),
                (
                    "financial_magnitude_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "financial_materiality_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("overall_rationale", models.TextField(blank=True, null=True)),
                ("related_documents", models.TextField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "iro",
                    models.ForeignKey(
                        db_column="iro_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessments.iro",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenantconfig",
                    ),
                ),
            ],
            options={
                "db_table": "risk_opp_assessment",
            },
        ),
        migrations.CreateModel(
            name="IRORelationship",
            fields=[
                (
                    "relationship_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("relationship_type", models.CharField(max_length=50)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.IntegerField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "source_iro",
                    models.ForeignKey(
                        db_column="source_iro_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_relationships",
                        to="assessments.iro",
                    ),
                ),
                (
                    "target_iro",
                    models.ForeignKey(
                        db_column="target_iro_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_relationships",
                        to="assessments.iro",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenantconfig",
                    ),
                ),
            ],
            options={
                "db_table": "iro_relationship",
            },
        ),
        migrations.CreateModel(
            name="ImpactMaterialityDef",
            fields=[
                ("def_id", models.AutoField(primary_key=True, serialize=False)),
                ("version_num", models.IntegerField()),
                ("dimension", models.CharField(max_length=50)),
                ("score_value", models.IntegerField()),
                ("definition_text", models.TextField()),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.IntegerField()),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenantconfig",
                    ),
                ),
            ],
            options={
                "db_table": "impact_materiality_def",
            },
        ),
        migrations.CreateModel(
            name="ImpactAssessment",
            fields=[
                (
                    "impact_assessment_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "impact_materiality_def_version_id",
                    models.IntegerField(blank=True, null=True),
                ),
                ("time_horizon", models.CharField(max_length=20)),
                (
                    "actual_or_potential",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "related_to_human_rights",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("scale_score", models.IntegerField(blank=True, null=True)),
                ("scale_rationale", models.TextField(blank=True, null=True)),
                ("scope_score", models.IntegerField(blank=True, null=True)),
                ("scope_rationale", models.TextField(blank=True, null=True)),
                ("irremediability_score", models.IntegerField(blank=True, null=True)),
                ("irremediability_rationale", models.TextField(blank=True, null=True)),
                ("likelihood_score", models.IntegerField(blank=True, null=True)),
                ("likelihood_rationale", models.TextField(blank=True, null=True)),
                (
                    "severity_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "impact_materiality_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("overall_rationale", models.TextField(blank=True, null=True)),
                ("related_documents", models.TextField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "iro",
                    models.ForeignKey(
                        db_column="iro_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessments.iro",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenantconfig",
                    ),
                ),
            ],
            options={
                "db_table": "impact_assessment",
            },
        ),
        migrations.CreateModel(
            name="FinMaterialityWeights",
            fields=[
                ("weight_id", models.AutoField(primary_key=True, serialize=False)),
                ("version_num", models.IntegerField()),
                ("dimension", models.CharField(max_length=50)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.IntegerField()),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenantconfig",
                    ),
                ),
            ],
            options={
                "db_table": "fin_materiality_weights",
            },
        ),
        migrations.CreateModel(
            name="FinMaterialityMagnitudeDef",
            fields=[
                ("def_id", models.AutoField(primary_key=True, serialize=False)),
                ("version_num", models.IntegerField()),
                ("score_value", models.IntegerField()),
                ("definition_text", models.TextField()),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.IntegerField()),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenantconfig",
                    ),
                ),
            ],
            options={
                "db_table": "fin_materiality_magnitude_def",
            },
        ),
        migrations.CreateModel(
            name="AuditTrail",
            fields=[
                ("audit_id", models.AutoField(primary_key=True, serialize=False)),
                ("entity_type", models.CharField(max_length=50)),
                ("entity_id", models.IntegerField()),
                ("action", models.CharField(max_length=50)),
                ("user_id", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("data_diff", models.JSONField(default=dict)),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenantconfig",
                    ),
                ),
            ],
            options={
                "db_table": "audit_trail",
            },
        ),
    ]
