# Generated by Django 4.2 on 2025-02-26 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('assessments', '0002_assessment_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenantconfig'),
        ),
    ]
