# Generated by Django 4.2 on 2025-03-09 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('assessments', '0003_alter_assessment_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField(default=1, help_text='Topic hierarchy level (1=highest, 3=lowest)')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('parent_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_topics', to='assessments.topic')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenantconfig')),
            ],
            options={
                'db_table': 'topic',
                'unique_together': {('tenant', 'name', 'level')},
            },
        ),
    ]
