# Generated by Django 4.2 on 2025-03-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irorelationship',
            name='relationship_type',
            field=models.CharField(help_text="Relationship type, e.g., 'split_from'", max_length=50),
        ),
    ]
