services:
  web:
    build: .
    command: >
      sh -c "
        echo '[WEB CONTAINER] Starting up...';
        until pg_isready -h db -p 5432 -U dma_user; do
          echo '[WEB CONTAINER] Waiting for database to become ready...';
          sleep 2;
        done;

        echo '[WEB CONTAINER] Running makemigrations (tenants + everything else)...';
        python manage.py makemigrations tenants;
        python manage.py makemigrations;

        echo '[WEB CONTAINER] Migrating shared schema...';
        python manage.py migrate_schemas --shared;

        echo '[WEB CONTAINER] Creating or updating default tenant...';
        python manage.py init_tenant --name=default --domain=localhost;

        echo '[WEB CONTAINER] Migrating tenant schemas...';
        python manage.py migrate_schemas --tenant;

        echo '[WEB CONTAINER] Initializing sample data...';
        python manage.py init_sample_data;

        echo '[WEB CONTAINER] Double-checking tables present in each tenant schema...';
        PGPASSWORD=password psql -h db -U dma_user -d dma_db -c \"\\dt tenant_tenant1.*\"
        PGPASSWORD=password psql -h db -U dma_user -d dma_db -c \"\\dt tenant_tenant2.*\"

        echo '[WEB CONTAINER] Collecting static files...';
        python manage.py collectstatic --noinput;

        echo '[WEB CONTAINER] Launching Gunicorn...';
        exec gunicorn core.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - .:/app
      - app_logs:/app/logs
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.local
      - DATABASE_URL=postgres://dma_user:password@db:5432/dma_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    # Add a healthcheck so Docker can verify Gunicorn is truly up
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: dma_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dma_db
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "5432:5432"
    # Already has a healthcheck
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dma_user -d dma_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  worker:
    build: .
    user: appuser
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.local
      - DATABASE_URL=postgres://dma_user:password@db:5432/dma_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      # If you want the worker to wait for web to be healthy as well, you could do:
      # web:
      #   condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
  app_logs: