[openrouter]
api_key = "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"
models = [
  #"google/gemini-2.0-pro-exp-02-05:free",
  # "google/gemini-2.0-flash-lite-preview-02-05:free",
  #"google/gemini-2.0-flash-thinking-exp:free",
  #"google/gemini-exp-1206:free",
  #"google/gemini-2.0-flash-thinking-exp-1219:free",
  #"google/gemini-2.0-flash-exp:free",
  "qwen/qwen2.5-vl-72b-instruct:free",
  #"deepseek/deepseek-r1-distill-llama-70b:free",
  #"deepseek/deepseek-r1:free",
  #"sophosympatheia/rogue-rose-103b-v0.2:free"
]
base_url = "https://openrouter.ai/api/v1"

[framework]
max_iterations = 1
validation_threshold = 0.7
refinement_rounds = 2

# NEW PARAMETER for two-mode operation:
# "python" => automatically call OpenRouter
# "manual" => skip calling OpenRouter, log prompts to CSV
mode = "python"